books/urls.py
from django.urls import path

from books import views

app_name = 'books'

urlpatterns = [
    path('list', views.BookListView.as_view(), name='list'),
    path('authors', views.AuthorListView.as_view(), name='authors'),
    path('', views.IndexView.as_view(), name='home'),
    path('detail/<slug:slug>', views.BookDetailView.as_view(), name='detail'),
    path('authors/books/<int:author_id>', views.AuthorBooks.as_view(), name='author_books'),
    path('book/create', views.CreateBook.as_view(), name='create_book'),
    path('book/update/<int:book_id>', views.UpdateBook.as_view(), name='update_book'),
    path('book/comment_create/<slug:slug>/<int:pk_book>', views.CommentCreate.as_view(), name='comment_create'),
    path('book/comment_delete/<slug:slug>/<int:comment_pk>', views.DeleteCommentView.as_view(), name='comment_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from core.settings import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
import django.contrib.auth.urls
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,)

from users import views

app_name = 'users'

# Auth urls
urlpatterns = [
        path('sigh_in', views.SighInView.as_view(), name='sigh_in'),
        path('', include("django.contrib.auth.urls"),),
        path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
        path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

books/models/Books.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse

from imagekit.models.fields import ImageSpecField
from imagekit.processors import ResizeToFit, Adjust, ResizeToFill

from users.models import Author


class Books(models.Model):
    name = models.CharField(verbose_name='awda', max_length=40)
    author = models.ManyToManyField(Author, )
    description = models.TextField(verbose_name='description of book', null=True, blank=True)
    cover = models.ImageField(upload_to='book/photo')
    cover_small = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1),
                                  ResizeToFill(50, 50)], source='cover')
    year_of_publishing = models.DateField(verbose_name='The year of publishing')
    archived = models.BooleanField(default=False)
    number_of_page = models.IntegerField(validators=[MinValueValidator(limit_value=10), ])
    slug = models.SlugField(max_length=40, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'slug': self.slug})

    def is_author(self, user):
        return self.author.filter(id=user.id).exists()

books/models/Comment.py
from django.db import models

from users.models import Author

from .Books import Books


class Comment(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comment by {self.author}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class CustomUser(AbstractUser):
    ...


class Author(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

books/forms.py
from django import forms

from .models import Books, Comment


class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        exclude = ('slug', 'cover_small', 'author')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'})
        }

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

CustomUser = get_user_model()


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ("username",)

books/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View, CreateView, UpdateView, TemplateView

from .models import Books, Comment
from .services import get_books, BookService, AuthorService
from .forms import BookForm, CommentForm

from users.models import Author


# Create your views here.


class IndexView(TemplateView):
    template_name = 'books/index.html'


class BookListView(ListView):
    template_name = 'books/list.html'
    queryset = get_books(model=Books)
    context_object_name = 'books'


class AuthorListView(ListView):
    template_name = 'books/authors.html'
    queryset = Author.objects.select_related('user').all()
    context_object_name = 'authors'


class AuthorBooks(View):
    template_name = 'books/list.html'

    def get(self, request, author_id: int):
        author_service = BookService()
        books = author_service.get_books_by_author(author_id)
        return render(request, self.template_name, {'books': books})


class BookDetailView(DetailView):
    model = Books
    context_object_name = 'book'
    template_name = 'books/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(book__slug=self.kwargs['slug'])
        context['form'] = CommentForm()
        return context


class CreateBook(LoginRequiredMixin, View):
    form_class = BookForm
    template_name = 'books/books_create.html'
    login_url = 'users/login'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=False)
            form.slug = form.cleaned_data.get('name')
            form.author = request.user.id
            form.save()
            return redirect('books:list')
        else:
            form = self.form_class()
            return render(request, self.template_name, {'form': form})


class UpdateBook(UpdateView):
    model = Books
    template_name = 'books/books_update.html'
    pk_url_kwarg = 'book_id'
    fields = '__all__'
    success_url = '/list'


class DeleteCommentView(LoginRequiredMixin, View):
    login_url = '/users/login'

    def get(self, request, slug, comment_pk):
        result = AuthorService()
        result.delete_comment(comment_pk)
        return redirect('books:detail', slug=slug)


class CommentCreate(LoginRequiredMixin, View):
    login_url = '/users/login'

    def post(self, request, slug, pk_book):
        author_service = AuthorService()
        author_service.set_comment(request, pk_book)
        return redirect('books:detail', slug=slug)

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate
from django.db import transaction
from django.contrib.auth import login

from .forms import UserCreateForm


# Create your views here.
class SighInView(View):
    def get(self, request):
        form = UserCreateForm()
        return render(request, 'registration/regist.html', {'form': form})

    # @transaction.atomic
    def post(self, request):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = form.save()
            user = authenticate(request, username=username, password=password)
            return redirect('book:list')
        else:
            form = UserCreateForm()
            messeage = 'Форма не валидна'
            return render(request, 'registration/regist.html', {'form': form, 'messeage': messeage})

books/templates/books/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>B</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
{%include 'include/header.html'%}
{%block content%}{%endblock%}
</body>
</html>

books/templates/books/authors.html
{%extends 'books/_base.html'%}

{%block content%}
<main class="container">
    {%for author in authors%}
    <h1><a href="{%url 'books:author_books' author.user.id%}">{{author.user.username}}</a></h1>
    {%endfor%}
</main>
{%endblock%}

books/templates/books/books_create.html
{%extends 'books/_base.html'%}

{%block content%}
<main class="container">
    <div class="row">
        {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
        {% endif %}
        <form class="form-control" action="{%url 'books:create_book'%}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Ok</button>
        </form>
    </div>
</main>
{%endblock%}

books/templates/books/books_update.html
{%extends 'books/_base.html'%}

{%block content%}
<main class="container">
  <form class="form-control"  action="" method="post">
    {%csrf_token%}
  {{form.as_p}}
    <input class="btn btn-primary" type="submit" value="Ok">
  </form>
</main>
{%endblock%}

books/templates/books/detail.html
{%extends 'books/_base.html'%}
{% load custom_filters %}
{%block content%}
<main class="container">
    <div class="row">
        <h1 class="">{{book.name}}</h1>
        <h3>{{book.date}}</h3>
        <h3>{{book.if}}</h3>
        {%if user.is_authenticated and book|is_author:user%}
        <a href="{%url 'books:update_book' book_id=book.id%}">изменить книгу</a>
        {%endif%}
        <div class="container">

        </div>
        <div class="row">
            <div class="container">
                <form class="form-control" action="{%url 'books:comment_create' book.slug book.id%}" method="post">
                    {%csrf_token%}
                    {{form.as_p}}
                    <button class="btn btn-dark" type="submit"> Submit</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="container">

                <div class="row d-flex justify-content-center">
                    <div class="col-md-8 col-lg-6">
                        <div class="card shadow-0 border" style="background-color: #f0f2f5;">

                            {%for comment in comments%}
                            <div class="card mb-4">
                                <div class="card-body">
                                    <p> {{comment.text}}</p>

                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center">
                                            <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp"
                                                 alt="avatar" width="25"
                                                 height="25"/>
                                            <p class="small mb-0 ms-2">{{comment.author}}</p>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <p class="small text-muted mb-0"><a
                                                    href="{%url 'books:comment_delete' slug=book.slug comment_pk=comment.id%}">Delete</a>
                                            </p>
                                            <i class="far fa-thumbs-up mx-2 fa-xs text-black"
                                               style="margin-top: -0.16rem;"></i>
                                            <p class="small text-muted mb-0">Update</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {%endfor%}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    </div>
    </div>
    </div>

</main>
{%endblock%}

books/templates/books/index.html
{%extends 'books/_base.html'%}

{%block content%}

{%endblock%}

books/templates/books/list.html
{%extends 'books/_base.html'%}
{%block content%}
<main class="container">
    <div class="row">
        {%for book in books%}

    </div>
    <div class="container py-5">
    <div class="row text-center text-white mb-5">
        <div class="col-lg-7 mx-auto">
            <h1 class="display-4">Product List</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            <ul class="list-group shadow">
                <!-- list group item-->
                <li class="list-group-item">
                    <!-- Custom content-->
                    <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            <h5 class="mt-0 font-weight-bold mb-2"><a class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"
           href="{{book.get_absolute_url}}">{{book.name}}</a></h5>

                            <div class="d-flex align-items-center justify-content-between mt-1">

                                <ul class="list-inline small">
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                                </ul>
                            </div>
                        </div><img src="{{book.cover.url}}" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                    </div> <!-- End -->
                </li> <!-- End -->
                <!-- list group item-->

                <!-- list group item -->
            </ul> <!-- End -->
        </div>
    </div>
</div>
</main>
{%endfor%}
{%endblock%}

books/templates/include/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="{%url 'books:list'%}" class="nav-link px-2 text-white">Books</a></li>

          <li><a href="{%url 'books:authors'%}" class="nav-link px-2 text-white">Authors</a></li>

        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
           {%if user.is_authenticated%}
          <a href="{%url 'books:create_book'%}" type="button" class="btn btn-outline-light me-2">Create book</a>
          <a href="{%url 'users:logout'%}" type="button" class="btn btn-warning">Logout</a>
          {%else%}


             <a href="{%url 'users:login'%}" type="button" class="btn btn-outline-light me-2">Login</a>
          <a href="{%url 'users:sigh_in'%}" type="button" class="btn btn-warning">Sign-up</a>

            {%endif%}

        </div>
      </div>
    </div>
  </header>